-- Programmers 03/01 2022
-- GROUP BY

1. 고양이와 개는 몇 마리 있을까
SELECT ANIMAL_TYPE, COUNT(ANIMAL_TYPE) AS count FROM ANIMAL_INS 
GROUP BY ANIMAL_TYPE 
ORDER BY ANIMAL_TYPE;

2. 동명 동물 수 찾기
SELECT NAME, COUNT(NAME) FROM ANIMAL_INS 
GROUP BY NAME 
HAVING COUNT(NAME) > 1 
ORDER BY NAME;

3. 입양 시각 구하기(1)
SELECT HOUR(DATETIME) AS HOUR, COUNT(HOUR(DATETIME)) AS COUNT FROM ANIMAL_OUTS 
GROUP BY HOUR(DATETIME) 
HAVING HOUR >= 9 AND HOUR <= 19 
ORDER BY 1;

4. 입양 시각 구하기(2)
SET @HOUR := -1; -- SET @변수명 := 값 (변수 선언)
SELECT (@HOUR := @HOUR + 1) AS HOUR, -- HOUR을 0부터 23까지
(SELECT COUNT(*) FROM ANIMAL_OUTS WHERE @HOUR = HOUR(DATETIME))
FROM ANIMAL_OUTS WHERE @HOUR < 23;