SELECT A.NAME NAME_X, B.NAME NAME_Y, COUNT(*) "장바구니 수"
FROM (SELECT DISTINCT C.NAME C.CART_ID FROM CART_PRODUCTS C) A
LEFT JOIN (SELECT DISTINCT D.NAME D.CART_ID FROM CART_PRODUCTS D) B
on A.CART_ID = B.CART_ID AND A.NAME != B.NAME
GROUP BY A.NAME, B.NAME
HAVING COUNT(*) > 0
ORDER BY A.NAME, B.NAME